object Dependencies {
    const val JPA = "org.springframework.boot:spring-boot-starter-data-jpa"
    const val SECURITY = "org.springframework.boot:spring-boot-starter-security"
    const val VALIDATION = "org.springframework.boot:spring-boot-starter-validation"
    const val WEB = "org.springframework.boot:spring-boot-starter-web"
    const val JACKSON = "com.fasterxml.jackson.module:jackson-module-kotlin"
    const val REFLECT = "org.jetbrains.kotlin:kotlin-reflect"
    const val JDK8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    const val JWT = "io.jsonwebtoken:jjwt:${DependencyVersions.JWT}"
    const val MYSQL = "com.mysql:mysql-connector-j"
    const val REDIS = "org.springframework.boot:spring-boot-starter-data-redis"
    const val QUERYDSL = "com.querydsl:querydsl-jpa:${DependencyVersions.QUERYDSL}"
    const val QUERYDSL_PROCESSOR = "com.querydsl:querydsl-apt:${DependencyVersions.QUERYDSL}:jpa"
    const val CONFIGURATION_PROCESSOR = "org.springframework.boot:spring-boot-configuration-processor"
    const val SECURITY_TEST = "org.springframework.security:spring-security-test"
    const val TEST = "org.springframework.boot:spring-boot-starter-test"
}